CREATE TABLE loan_histories (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    loan_no VARCHAR(255) NOT NULL UNIQUE,
    status ENUM('NOT YET REGISTERED', 'IN PROGRESS DOCUMENTS UPLOADED', 'LOAN APPROVED', 'LOAN SANCTIONED', 'AMOUNT CREDITED') NOT NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL
);


INSERT INTO loan_histories (loan_no, status, created_at, updated_at) VALUES
('LN001', 'NOT YET REGISTERED', NOW(), NOW()),
('LN002', 'IN PROGRESS DOCUMENTS UPLOADED', NOW(), NOW()),
('LN003', 'LOAN APPROVED', NOW(), NOW()),
('LN004', 'LOAN SANCTIONED', NOW(), NOW()),
('LN005', 'AMOUNT CREDITED', NOW(), NOW());
